"""
GigCredit — m2cgen Dart Export
================================
Converts trained sklearn/XGBoost pillar models and meta-learner → pure Dart arithmetic functions.
Also writes deterministic P5/P7 scorecards and scoring_constants.dart.

Output files in ml_pipeline/output/dart_exports/:
  p1_scorer.dart          ← XGBoost P1 → Dart (m2cgen)
  p2_scorer.dart          ← XGBoost P2 → Dart (m2cgen)
  p3_scorer.dart          ← XGBoost P3 → Dart (m2cgen)
  p4_scorer.dart          ← XGBoost P4 → Dart (m2cgen)
  p6_scorer.dart          ← XGBoost P6 → Dart (m2cgen)
  meta_scorer.dart        ← XGBoost Meta-Learner → Dart (m2cgen)
  scorecard_p5.dart       ← Deterministic weighted mean (identity/work docs)
  scorecard_p7.dart       ← Deterministic weighted mean (social accountability)
  scoring_constants.dart  ← Feature order and helper functions
"""

import json
import sys
from pathlib import Path

import joblib
import m2cgen as m2c

# Pillar model → (function name, input feature count)
PILLAR_MAP = [
    ("p1", "scoreP1", 13),
    ("p2", "scoreP2", 15),
    ("p3", "scoreP3",  9),
    ("p4", "scoreP4", 12),
    ("p6", "scoreP6", 11),
]


def _dart_file_header(description: str) -> str:
    return (
        "// ============================================================\n"
        f"// GigCredit — {description}\n"
        "// AUTO-GENERATED by export_m2cgen.py — DO NOT EDIT\n"
        "// ============================================================\n\n"
        "import 'dart:math' as math;\n\n"
    )


def write_m2cgen_scorer(
    model_path: Path,
    out_path: Path,
    fn_name: str,
    description: str,
) -> None:
    """Load a .pkl model, export to Dart via m2cgen, wrap in file."""
    model = joblib.load(model_path)
    dart_body = m2c.export_to_dart(model, function_name=fn_name)

    wrapped = (
        _dart_file_header(description)
        + dart_body.rstrip()
        + "\n\n"
        + f"/// Clamp output of [{fn_name}] to [0.0, 1.0].\n"
        + f"double {fn_name}Safe(List<double> input) {{\n"
        + f"  final raw = {fn_name}(input);\n"
        + "  return raw.clamp(0.0, 1.0);\n"
        + "}\n"
    )
    out_path.write_text(wrapped, encoding="utf-8")
    print(f"  ok {out_path.name}")


def write_m2cgen_meta_scorer(model_path: Path, out_path: Path, feat_order: list) -> None:
    """Export the Meta-Learner XGBRegressor to Dart."""
    model = joblib.load(model_path)
    dart_body = m2c.export_to_dart(model, function_name="_scoreMetaRaw")

    wrapped = (
        _dart_file_header("Meta-Learner RandomForest Scorer (19 features)")
        + dart_body.rstrip()
        + "\n\n"
        + "/// RandomForest Regressor returns a continuous probability-like score [0.0, 1.0].\n"
        + "double scoreMeta(List<double> input) {\n"
        + "  assert(input.length == 19, 'Meta-Learner expects exactly 19 features.');\n"
        + "  final double rawVal = _scoreMetaRaw(input);\n"
        + "  return rawVal.clamp(0.0, 1.0);\n"
        + "}\n"
    )
    out_path.write_text(wrapped, encoding="utf-8")
    print(f"  ok {out_path.name}")


def write_scorecard_p5(out_path: Path) -> None:
    """P5 Work & Identity: uniform weighted mean of 18 features (indices 49-66)."""
    weights = {
        49: 0.08, 50: 0.07, 51: 0.07, 52: 0.07, 53: 0.06, 54: 0.05, 55: 0.05,
        56: 0.05, 57: 0.05, 58: 0.06, 59: 0.06, 60: 0.05, 61: 0.06, 62: 0.04,
        63: 0.03, 64: 0.04, 65: 0.04, 66: 0.07,
    }
    total_w = sum(weights.values())
    terms = " +\n        ".join(f"input[{i - 49}] * {w:.2f}" for i, w in weights.items())
    content = (
        _dart_file_header("P5 Work & Identity Scorecard (Deterministic)")
        + "/// Weighted mean of 18 work/identity features.\n"
        + "/// Input: features[49..66] normalized to [0.0, 1.0]\n"
        + "double scoreP5(List<double> input) {\n"
        + "  assert(input.length == 18, 'P5 expects 18 features (f49-f66)');\n"
        + f"  final raw = (\n        {terms}\n      ) / {total_w:.2f};\n"
        + "  return raw.clamp(0.0, 1.0);\n"
        + "}\n"
    )
    out_path.write_text(content, encoding="utf-8")
    print(f"  ok {out_path.name}")


def write_scorecard_p7(out_path: Path) -> None:
    """P7 Social Accountability: weighted mean of 17 features (indices 78-94)."""
    weights = {
        78: 0.08, 79: 0.06, 80: 0.05, 81: 0.06, 82: 0.06, 83: 0.06, 84: 0.06,
        85: 0.04, 86: 0.05, 87: 0.05, 88: 0.06, 89: 0.07, 90: 0.05, 91: 0.06,
        92: 0.06, 93: 0.05, 94: 0.08,
    }
    total_w = sum(weights.values())
    terms = " +\n        ".join(f"input[{i - 78}] * {w:.2f}" for i, w in weights.items())
    content = (
        _dart_file_header("P7 Social Accountability Scorecard (Deterministic)")
        + "/// Weighted mean of 17 social accountability features.\n"
        + "/// Input: features[78..94] normalized to [0.0, 1.0]\n"
        + "double scoreP7(List<double> input) {\n"
        + "  assert(input.length == 17, 'P7 expects 17 features (f78-f94)');\n"
        + f"  final raw = (\n        {terms}\n      ) / {total_w:.2f};\n"
        + "  return raw.clamp(0.0, 1.0);\n"
        + "}\n"
    )
    out_path.write_text(content, encoding="utf-8")
    print(f"  ok {out_path.name}")


def write_scoring_constants(out_path: Path, coeffs: dict) -> None:
    """Emit scoring helper constants and functions."""
    feat_order = coeffs["feature_order"]

    content = (
        _dart_file_header("Meta-Learner Scoring Constants")
        + "// Feature order for meta-learner input (19 elements):\n"
        + "// " + ", ".join(feat_order) + "\n\n"
        + "/// Convert a probability to GigCredit score (300-900 scale).\n"
        + "int probabilityToScore(double probability) =>\n"
        + "    (probability * 600 + 300).round().clamp(300, 900);\n"
        + "\n"
        + "/// Grade from score.\n"
        + "String scoreToGrade(int score) {\n"
        + "  if (score >= 800) return 'A+';\n"
        + "  if (score >= 750) return 'A';\n"
        + "  if (score >= 700) return 'B+';\n"
        + "  if (score >= 650) return 'B';\n"
        + "  if (score >= 600) return 'C+';\n"
        + "  if (score >= 550) return 'C';\n"
        + "  return 'D';\n"
        + "}\n"
        + "\n"
        + "/// Risk level from score.\n"
        + "String scoreToRiskLevel(int score) {\n"
        + "  if (score >= 700) return 'Low';\n"
        + "  if (score >= 580) return 'Medium';\n"
        + "  return 'High';\n"
        + "}\n"
    )
    out_path.write_text(content, encoding="utf-8")
    print(f"  ok {out_path.name}")


def main() -> None:
    model_dir  = Path("ml_pipeline/output/models")
    config_dir = Path("ml_pipeline/output/json_configs")
    out_dir    = Path("ml_pipeline/output/dart_exports")
    out_dir.mkdir(parents=True, exist_ok=True)

    print("Exporting pillar models to Dart via m2cgen …")

    for name, fn_name, n_feats in PILLAR_MAP:
        model_path = model_dir / f"{name}.pkl"
        if not model_path.exists():
            print(f"ERROR: {model_path} not found. Run train_pillars.py first.")
            sys.exit(1)
        write_m2cgen_scorer(
            model_path,
            out_dir / f"{name}_scorer.dart",
            fn_name,
            f"P{name[1].upper()} Pillar Scorer ({n_feats} features)",
        )

    print("Exporting Meta-Learner (RandomForestRegressor) to Dart …")
    meta_path = model_dir / "meta_rf.pkl"
    if not meta_path.exists():
        print("ERROR: meta_rf.pkl missing.")
        sys.exit(1)
    
    coeffs_path = config_dir / "meta_coefficients.json"
    if not coeffs_path.exists():
        print("ERROR: meta_coefficients.json missing.")
        sys.exit(1)
    coeffs = json.loads(coeffs_path.read_text(encoding="utf-8"))

    write_m2cgen_meta_scorer(meta_path, out_dir / "meta_scorer.dart", coeffs["feature_order"])

    print("Writing deterministic scorecards …")
    write_scorecard_p5(out_dir / "scorecard_p5.dart")
    write_scorecard_p7(out_dir / "scorecard_p7.dart")

    print("Writing scoring_constants.dart …")
    write_scoring_constants(out_dir / "scoring_constants.dart", coeffs)

    print(f"\nAll Dart exports ready in {out_dir}/")


if __name__ == "__main__":
    main()
