// ============================================================
// GigCredit — P5 Work & Identity Scorecard (Deterministic)
// AUTO-GENERATED by export_m2cgen.py — DO NOT EDIT
// ============================================================

import 'dart:math' as math;

/// Weighted mean of 18 work/identity features.
/// Input: features[49..66] normalized to [0.0, 1.0]
double scoreP5(List<double> input) {
  assert(input.length == 18, 'P5 expects 18 features (f49-f66)');
  final raw = (
        input[0] * 0.08 +
        input[1] * 0.07 +
        input[2] * 0.07 +
        input[3] * 0.07 +
        input[4] * 0.06 +
        input[5] * 0.05 +
        input[6] * 0.05 +
        input[7] * 0.05 +
        input[8] * 0.05 +
        input[9] * 0.06 +
        input[10] * 0.06 +
        input[11] * 0.05 +
        input[12] * 0.06 +
        input[13] * 0.04 +
        input[14] * 0.03 +
        input[15] * 0.04 +
        input[16] * 0.04 +
        input[17] * 0.07
      ) / 1.00;
  return raw.clamp(0.0, 1.0);
}
