// ============================================================
// GigCredit — P5 Work & Identity Scorecard (Deterministic)
// AUTO-GENERATED by export_m2cgen.py — DO NOT EDIT
// ============================================================

import 'dart:math' as math;

/// Weighted mean of 18 work/identity features.
/// Input: features[49..66] normalized to [0.0, 1.0]
double scoreP5(List<double> input) {
  assert(input.length == 18, 'P5 expects 18 features (f49-f66)');
  final raw = input.reduce((a, b) => a + b) / 18.0;
  return raw.clamp(0.0, 1.0);
}
