// ============================================================
// GigCredit — P7 Social Accountability Scorecard (Deterministic)
// AUTO-GENERATED by export_m2cgen.py — DO NOT EDIT
// ============================================================

import 'dart:math' as math;

/// Weighted mean of 17 social accountability features.
/// Input: features[78..94] normalized to [0.0, 1.0]
double scoreP7(List<double> input) {
  assert(input.length == 17, 'P7 expects 17 features (f78-f94)');
  final raw = input.reduce((a, b) => a + b) / 17.0;
  return raw.clamp(0.0, 1.0);
}
