// ============================================================
// GigCredit — Meta-Learner Scoring Constants
// AUTO-GENERATED by export_m2cgen.py — DO NOT EDIT
// ============================================================

import 'dart:math' as math;

// Feature order for meta-learner input (19 elements):
// p1, p2, p3, p4, p5, p6, p7, w_platform, w_vendor, w_trades, w_free, p1_x_platform, p2_x_platform, p1_x_vendor, p2_x_vendor, p1_x_trades, p2_x_trades, p1_x_free, p2_x_free

/// Convert a probability to GigCredit score (300-900 scale).
int probabilityToScore(double probability) =>
    (probability * 600 + 300).round().clamp(300, 900);

/// Grade from score.
String scoreToGrade(int score) {
  if (score >= 800) return 'A+';
  if (score >= 750) return 'A';
  if (score >= 700) return 'B+';
  if (score >= 650) return 'B';
  if (score >= 600) return 'C+';
  if (score >= 550) return 'C';
  return 'D';
}

/// Risk level from score.
String scoreToRiskLevel(int score) {
  if (score >= 700) return 'Low';
  if (score >= 580) return 'Medium';
  return 'High';
}
