// ============================================================
// GigCredit — P7 Social Accountability Scorecard (Deterministic)
// AUTO-GENERATED by export_m2cgen.py — DO NOT EDIT
// ============================================================

import 'dart:math' as math;

/// Weighted mean of 17 social accountability features.
/// Input: features[78..94] normalized to [0.0, 1.0]
double scoreP7(List<double> input) {
  assert(input.length == 17, 'P7 expects 17 features (f78-f94)');
  final raw = (
        input[0] * 0.08 +
        input[1] * 0.06 +
        input[2] * 0.05 +
        input[3] * 0.06 +
        input[4] * 0.06 +
        input[5] * 0.06 +
        input[6] * 0.06 +
        input[7] * 0.04 +
        input[8] * 0.05 +
        input[9] * 0.05 +
        input[10] * 0.06 +
        input[11] * 0.07 +
        input[12] * 0.05 +
        input[13] * 0.06 +
        input[14] * 0.06 +
        input[15] * 0.05 +
        input[16] * 0.08
      ) / 1.00;
  return raw.clamp(0.0, 1.0);
}
